###########################
## CUSTOM SCRATCHPADS #####
###########################

###########################
## Toggle for Pulse Audio
###########################
# 1. Define appearance rules

for_window [app_id="pavucontrol"] {
    floating enable
    resize set width 1800 px height 1015 px
    move absolute position center
    move scratchpad
}
# Set the key bind
bindsym $mod+u [app_id="pavucontrol"] scratchpad show, move position center
# Run Pulse Audio
exec_always pavucontrol

###########################
# Toggle for Wezterm ######
###########################

# Define $term_id variable
set $term_id wezterm-scratchpad

# 1. Define appearance rules
for_window [app_id="$term_id"] {
    floating enable
    move scratchpad
}
# Set the key bind
bindsym F12 [app_id="$term_id"] scratchpad show, resize set 1800 px 1015 px, move position center

# UPDATED: Run Wezterm for scratchpad and set the title
exec_always wezterm start --class $term_id -- bash -c "wezterm cli set-tab-title 'Bashy Fun 😀'; exec bash"

#############################
# Toggle for Keepassxc ######
#############################

# Define the actual app_id KeePassXC uses
set $keepass_id org.keepassxc.KeePassXC

# 1. Match the app and send to scratchpad
for_window [app_id="$keepass_id"] {
    floating enable
    move scratchpad
}

# 2. Toggle bind
bindsym F1 [app_id="$keepass_id"] scratchpad show, resize set 1800 px 1015 px, move position center

# 3. Start it (KeePassXC doesn't take a custom --class like a terminal)
exec_always keepassxc


