##############################
## Screenshot stuff (grim) ###
##############################

bindsym Print exec grim
bindsym --release $mod+Shift+s exec "/usr/bin/grimshot save area"

###################################
## Screenshot stuff (flameshot) ###
###################################

# Match ONLY the capture overlay (Title is exactly 'flameshot')
for_window [app_id="flameshot" title="^flameshot$"] {
    floating enable
    border none
    fullscreen enable global
}

# Match the Save dialog (Title is exactly 'Save screenshot')
for_window [app_id="flameshot" title="Save screenshot"] {
    floating enable
    fullscreen disable
    resize set width 1600 px height 900
    move position center
}



bindsym $mod+Shift+f exec "QT_STYLE_OVERRIDE=breeze QT_QPA_PLATFORMTHEME=kde flameshot gui"
