# Tell tmux to use 256color profiles natively
set -g default-terminal "tmux-256color"

# Force true color (RGB) support over terminal protocol links
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ",xterm-256color:Tc"


# Adding clipboard sharing across SSH sessions, Wezterm tabs... what have you
set -s set-clipboard on

# Adding mouse scrolling
set -g mouse on

# Start numbering at 1 instead of 0
set-option -g base-index 1
set-option -g pane-base-index 1

# Increase scrollback buffer size
set-option -g history-limit 10000 

# Open new panes/windows in same directory as current pane/window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Adding a bind to reload config and refresh screen
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"; refresh-client -S
##
##
# Setting that's exclusively for servers, probably won't ever need it
##
##
set-option -s focus-events on


##
##
# Styling
##
##

# Set color variables
FG=#F8DCC0
BG=#1F1D45
BLACK=#050404
RED=#BD0013
GREEN=#4AB14A
YELLOW=#E7741D
BLUE=#0F4AC6
MAGENTA=#665993
CYAN=#70A598
WHITE=#F8DCC0
PURPLE=#1F1D45
BRBLACK=#4D485F
BRRED=#FC5F5A
BRGREEN=#9EFF6E
BRYELLOW=#EFC11A
BRBLUE=#1997FC
BRMAGENTA=#9B5953
BRCYAN=#9FF1E2
BRWHITE=#F6F6F4

# Set powerline unicode variables
HALF_ROUND_LEFT="\uE0B6"
HALF_ROUND_RIGHT="\uE0B4"
DIGI_RIGHT="\uE0C4"
DIGI_LEFT="\uE0C5"
FLAME_LEFT="\uE0C2"
FLAME_RIGHT="\uE0C0"
TRIANGLE_LEFT="\uE0B2"
TRIANGLE_RIGHT="\uE0B0"


# Foreground/background
set-option -g status-style bg=${BLACK},fg=${FG}

# Customizing left-hand side of status bar 

# Setting left-hand styles
set-option -g status-left "#[bg=${YELLOW},fg=${BLACK}] \
#[bg=${YELLOW},fg=${BLACK}]#S\
#[bg=${YELLOW},fg=${BLACK}] \
#[bg=${BLACK},fg=${YELLOW}]\
${TRIANGLE_RIGHT}"

# Show hostname on right-hand side, and style
set-option -g status-right "\
#[fg=${BLACK},bg=${YELLOW}]${TRIANGLE_RIGHT}\
#[bg=${YELLOW},fg=${BLACK}] \
#[bg=${YELLOW},fg=${BLACK}]#{host_short}"

# Increasing the right and left sides max length
set-option -g status-right-length 100
set-option -g status-left-length 100

# Center panes (tabs) in pane display area
set-option -g status-justify centre

#Styling inactive windows
set-option -g window-status-format "\
 #I\
#[fg=${BRRED}]:\
#[fg=default]#W \
"
#Styling active window
set-option -g window-status-current-format "\
#[bg=${BRBLACK},fg=${BLACK}]${TRIANGLE_RIGHT} \
#[bg=${BRBLACK},fg=${WHITE}]#I\
#[fg=${BRYELLOW}]:\
#[fg=default]#W \
#[bg=${BLACK},fg=${BRBLACK}]${TRIANGLE_RIGHT}
"

# Getting rid of separator in between the windows
set-option -g window-status-separator ""
