# Tell tmux to use 256color profiles natively
set -g default-terminal "tmux-256color"

# Force true color (RGB) support over terminal protocol links
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ",xterm-256color:Tc"


# Adding clipboard sharing across SSH sessions, Wezterm tabs... what have you
set -s set-clipboard on

# Adding mouse scrolling
set -g mouse on

# Start numbering at 1 instead of 0
set-option -g base-index 1
set-option -g pane-base-index 1

# Increase scrollback buffer size
set-option -g history-limit 10000 

# Open new panes/windows in same directory as current pane/window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

##
##
# Setting that's exclusively for servers, probably won't ever need it
##
##
set-option -s focus-events on


##
##
# Styling
##
##

