# --- Core Graphics Engine ---
WLR_RENDERER=vulkan

# --- Wayland Desktop Standards ---
XDG_CURRENT_DESKTOP=wlroots
XDG_SESSION_DESKTOP=wlroots
XDG_SESSION_TYPE=wayland

# --- Hardware & Driver Overrides ---
MOZ_ENABLE_WAYLAND=1
SDL_VIDEODRIVER=wayland
QT_QPA_PLATFORM=wayland;xcb

# --- NVIDIA Laptop Specifics ---
WLR_NO_HARDWARE_CURSORS=1
LIBVA_DRIVER_NAME=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia

